### PR TITLE
Check in synth.py and conform to google node repo standards

### LINKED ISSUE #11: Set up CI

### PR DESCRIPTION
**Pull request by kinwa91**
fixes #11

### CODE REVIEW

**Comment by kinwa91** [comment]
@GoogleCloudPlatform/node-team - need help enabling Circle for this one :)

**Comment by JustinBeckwith** [comment]
Need to add the docs directory to the .gitignore :)

**Comment by JustinBeckwith** [comment]
@kinwa91 do you have all the rights you need to modify the CircleCI env vars and stuff?

**Comment by kinwa91** [comment]
Yup. I will put in the good stuff. :)

**Comment by kinwa91** [comment]
@stephenplusplus tests in this repo calls the actual service?

**Comment by kinwa91** [comment]
Got it. I'll start a thread to move those to system-test and rewrite some unit tests.

**Pull request merged**
